### PR TITLE
Setup project

### PR DESCRIPTION
**Pull request by JTLee98**
- made empty project
- added the following plugins:
   - Object VFX: [SRD_BitmapUpGrade](http://sumrndm.site/bitmap-upgrade/) 
   - [YEP_SaveEventLocations](http://www.yanfly.moe/wiki/Save_Event_Locations_(YEP)) 
   - 3D View: [MV3D](https://github.com/Dread-chan/MV3D) 
   - [GitCompatibilityPatch](https://github.com/Luther-1/RMMV-GitCompat) 
   - Continuous Movement etc: [AltimitMovement](https://github.com/AltimitSystems/mv-plugins/tree/master/movement) 
   - Point and Click mechanics [TDDP_MouseSystemEx](https://github.com/TorD/TDDP-Repo/blob/master/TDDP_MouseSystemEx.js) 
- disabled the following plugins:
   - MadeWithMV

### CODE REVIEW

**Comment by JTLee98** [comment]
PnCInventory plugin is having trouble, will mark ready for review after fixing it

**Comment by JTLee98** [comment]
> [Point and Click Inventory](https://forums.rpgmakerweb.com/index.php?threads/point-and-click-inventory-iconid-pictures-ver-2-10-06-2019.102034/) plugin is having trouble, will mark ready for review after fixing it and committing
-> Done! 

next: make the menu text english

**Comment by JTLee98** [comment]
> next: make the menu text english

-> Done!

**Comment by JTLee98** [comment]
ok i think i'll just leave this at here for now

**Review by TannerLH — APPROVED** [review]
Looks good to me

**Comment by JTLee98** [comment]
please test these changes are not breaking for you before approving!

**Review by ChesterLuna — APPROVED** [review]

**Pull request merged**
